server:
  port: 8083

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/authenticator?schema=public

keycloak:
  cors: true
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: hbsites-realm.json